name: Restaurante continues Integration pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
 run:
  working-directory: projeto/back-end

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10' 
      - run: pip install ruff
      - run: ruff check . && ruff fix .
      - run: ruff fix .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Corrige a estilização do código'

  ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context:  "{{defaultContext}}:projeto/back-end/"
          push: true
          tags: josedembo/painelcovid:${{ github.sha }}
